name: CI

on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - '*'

defaults:
  run:
    shell: bash

env:
  # Go needs absolute directories, using the $HOME variable doesn't work here.
  GOPATH: /home/runner/work/go

jobs:
  rust-compilation-check:
    name: Rust compilation check
    runs-on: ubuntu-24.04
    steps:
      - name: git checkout
        uses: actions/checkout@v4

      - name: assert wrapper unchanged
        run: make check-wrapper-compiled
  rust-checks:
    name: Rust checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt
      - run: |
          cd wrapper
          cargo fmt --check
          cargo test
          cargo clippy -- -A clippy::missing_safety_doc
  go-unit-test:
    name: Go unit tests
    runs-on: ubuntu-latest
    steps:
      - name: git checkout
        uses: actions/checkout@v4

      - name: Setup go
        uses: actions/setup-go@v5
        with:
          go-version-file: ./go.mod

      - name: Run unit test
        run: make unit-test
